name: Container Remediation Self-Test

on:
  workflow_dispatch:
    inputs:
      image-ref:
        description: Container image to scan
        required: true
        default: '613957054632.dkr.ecr.us-east-1.amazonaws.com/kernel/api:main'

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  remediate:
    uses: ./.github/workflows/container-remediation.yml
    with:
      image-ref: ${{ inputs.image-ref }}
      go-version-file: ''
      ecr-role-to-assume: 'arn:aws:iam::613957054632:role/github-actions-ecr-pusher'
    secrets: inherit
